name: Docker push on Github registry

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          imageName: gopher
          imageTag: 0.0.1